### get all exercises
GET http://localhost:3001/api/exercises

### add exercise
POST http://localhost:3001/api/exercises
Content-Type: application/json

{
    "name": "incline bench press",
    "instructions": "Set your feet at a stable position and lie on a bench inclined at approximately 30 degrees with the racked bar slightly behind your head. Place your hands slightly wider than shoulder width on the bar, ensuring the grip is even on both sides and the width is comfortable. Leverage yourself against the bar to retract and depress your scapula, and push with your legs to reinforce your lower back arch. Unrack the bar and bring it forward over your chest with straight arms. Lower the bar in a controlled manner until it touches your upper chest, before pressing it back to its starting position, all while maintaining the same scapula position and lower back arch.",
    "primaryMuscleGroups": ["arms", "chest"],
    "secondaryMuscleGroups": ["shoulders"],
    "primaryMuscles": ["upper chest", "triceps"],
    "secondaryMuscles": ["anterior deltoid", "lower chest"]
}

### delete exercise by id
DELETE http://localhost:3001/api/exercises/63dd38feb5a222be4573e666

###

GET http://localhost:3001/api/exercises/63dd68eefed1e86b9a4dada9

### clear exercise database DEV
DELETE http://localhost:3001/api/clear/exercises

### initialize exercise database DEV
POST http://localhost:3001/api/init/exercises
