### initialize exercise database DEV
POST http://localhost:3001/api/init/exercises

### initialize sets database DEV NOTE AFTER INIT EXERC
POST http://localhost:3001/api/init/sets

### initialize planned sets database DEV NOTE AFTER INIT EXERC
POST http://localhost:3001/api/init/plannedsets

### initialize planned workout database DEV NOTE AFTER INIT EXERC
POST http://localhost:3001/api/init/plannedworkouts