### get all sets
GET http://localhost:3001/api/plannedsets

### add set
POST http://localhost:3001/api/plannedsets
Content-Type: application/json

{
    "type": "work",
    "exercise": "63dd68eefed1e86b9a4dada4"
}


### clear sets database DEV
DELETE http://localhost:3001/api/clear/plannedsets