### get all routines
GET http://localhost:3001/api/routines

### add routine
POST http://localhost:3001/api/routines
Content-Type: application/json

{
    "name": "test routine",
    "notes": "awesome test routine",
    "weeks": [
         [
                "63ee290358c6498edaeb7c51",
                "63f0c7fa9b7763193be1a228"
            ]
        
        
    ]
}