### get all sets
GET http://localhost:3001/api/sets/63e671c055a0cc3ca3859a01

### add set
POST http://localhost:3001/api/sets
Content-Type: application/json

{
    "_id": "63e4e7cccfbda2b2500a8a84",
    "type": "work",
    "weight": 50,
    "reps": 12,
    "exercise": "63dd68eefed1e86b9a4dada4"
}

### add [set]
POST http://localhost:3001/api/sets
Content-Type: application/json

["hello"]

### get sets by exercise ID
GET http://localhost:3001/api/sets/exercise/63dd4dade477342a1fe45227

### clear sets database DEV
DELETE http://localhost:3001/api/clear/sets