### get all users
GET http://localhost:3001/api/users

### add user
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "User9",
    "name": "User",
    "password": "password"
}