### get all workouts
GET http://localhost:3001/api/workouts

### add workout NOTE: CHECK REFS
POST http://localhost:3001/api/workouts
Content-Type: application/json

{
    "name": "Test Workout",
    "notes": "Great workout for testing purposes",
    "duration": 60,
    "exercises": [],
    "sets": []
}